name: 0.1.$(Rev:r)

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - images/*
      - README.md

pool:
  vmImage: "ubuntu-latest"

# Shared Templates
# ----------------
resources:
  repositories:
    - repository: pipelineTemplates
      type: git
      name: investec-cloud-experience/azure-pipeline-templates
      ref: refs/heads/main
    - repository: securityTemplates
      type: git
      name: ice-infrastructure-as-code/security-templates
      ref: refs/heads/main

# Variables
# ---------

variables:
  - name: isMain
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}

  - name: azurermAcrPushServiceConnection
    value: azurerm-icebox-push-prod-001-sandbox

  - name: dockerAcrPushServiceConnection
    value: dr-icebox-push-prod-001-sandbox

  - name: containerImageName
    value: sandbox/airoadshowmumbai

# Stages
# ------

extends:
  template: default-base-template.yml@securityTemplates
  parameters:
    stages:
      - stage: BuildContainerImage
        ${{ if eq(variables.isMain, true) }}:
          displayName: Publish container image
        ${{ else }}:
          displayName: Build container image
        jobs:
          - template: jobs/containers/build.yml@pipelineTemplates
            parameters:
              containerRegistryConnectionName: ${{ variables.dockerAcrPushServiceConnection }}
              containerRegistryAzureRmConnection: ${{ variables.azurermAcrPushServiceConnection }}
              imageName: ${{ variables.containerImageName }}
              hadolintAdditionalArguments: "--ignore DL3003"
              tagsAsMultilineString: |
                $(setContainerImageTag.containerImageTag)
              # Build and push is on main, else build only
              ${{ if eq(variables.isMain, true) }}:
                command: buildAndPush
              ${{ else }}:
                command: buildAndPush
              beforeSteps:
                # This sets a $(setContainerImageTag.containerImageTag) variable with a good tagging convention as a helper
                # Convention is {branch name}-{commit short hash}
                - template: steps/containers/set-container-image-tag.yml@pipelineTemplates

                # This unlocks the tag if it exists - note this is an example and not necessarily a good practice
                - template: steps/unlock-acr-image-tag.yml@pipelineTemplates
                  parameters:
                    azureRmConnection: ${{ variables.azurermAcrPushServiceConnection }}
                    imageName: ${{ variables.containerImageName }}
                    imageTag: latest
