name: $(Date:yyyyMMdd)$(Rev:rr)
trigger: none

resources:
  repositories:
    - repository: securityTemplates
      type: git
      name: ice-infrastructure-as-code/security-templates
      ref: refs/heads/main
    - repository: pipelineTemplates
      type: git
      name: investec-cloud-experience/azure-pipeline-templates
      ref: refs/heads/main

variables:
  - name: azurermAcrPullServiceConnection
    value: azurerm-icebox-pull-prod-001-sandbox
  - name: azurermRgServiceConnection
    value: azurerm-airoadshowmumbai-sbx-001
  - name: resourceGroupName
    value: rg-airoadshowmumbai-sbx-001
  - name: location
    value: northeurope
  - name: dockerAcrPullServiceConnection
    value: dr-icebox-pull-prod-001-sandbox

extends:
  template: default-base-template.yml@securityTemplates
  parameters:
    stages:
    - stage: Build
      displayName: Build
      jobs:      
      - job: ArmDeploy
        displayName: ArmDeploy
        steps:
        - task: ServiceConnectionMetaGeneric@1
          displayName: "Get Registry Service Connection Details"
          inputs:
            registryServiceConnection: ${{ variables.dockerAcrPullServiceConnection }}
            usernameOutput: registryUsername
            passwordOutput: registryPassword
        - template: steps/bicep/deploy-validate.yml@pipelineTemplates
          parameters:
            serviceConnection: ${{ variables.azurermRgServiceConnection }}
            registryServiceConnection: ${{ variables.azurermAcrPullServiceConnection }}
            templatePath: infra/main.bicep
            resourceGroupName: ${{ variables.resourceGroupName }}
            location: ${{ variables.location }}
            deploymentMode: Incremental
            overrideParameters: >-
              -containerRegistryPassword $(registryPassword)
              -containerRegistryUsername $(registryUsername)
          
              
              
# -tags {"owner": "$(owner)", "costCenter": "$(costCenter)", "application": "$(application)", "description": "$(description)", "repo": "$(repo)", "branch": "$(Build.SourceBranchName)"}
# -logAnalyticsWorkspaceName $(arcLogAnalyticsWorkspace)
# -keyVaultName $(arcKeyVault)